# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
#指定Mybatis的实体目录
  type-aliases-package: com.hyl.model.entity



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/universe?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: user-manage-center
#  session失效时间
  session:
    timeout: 86400
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  openapi:
    title: 用户中心-api文档
    description: "用户中心**接口**文档"
    email: 1257635375@qq.com
    concat: RugingHYL
    url: https://github.com/RustHYL
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://github.com/RustHYL
    group:
      test1:
        group-name: center
        api-rule: package
        api-rule-resources:
          - com.hyl.controller

